// src/lib/desarrolladores.en.ts
// English mirror of src/lib/desarrolladores.ts — same slugs, same mocks, same
// verified numbers. Change a fact there and here in the same commit.
import type { DevPage } from './desarrolladores';

const UPDATED = '2026-09-30';

export const DEV_PAGES_EN: DevPage[] = [
    {
        slug: 'api',
        nav: 'REST API',
        eyebrow: 'REST API',
        titulo: 'Quote, invoice and collect from your own code.',
        sub: "Cord's REST API creates and reads quotes, clients, products and invoices with a Bearer key, and runs the same actions as the app: send, approve, issue or record a payment. Predictable JSON responses, an OpenAPI spec and test keys that work in an environment isolated from your real data.",
        metaTitle: 'Quotes and invoicing REST API — Cord for developers',
        metaDescription: 'Create quotes, clients, products and invoices through a REST API with a Bearer key. Idempotency-Key, cursor-based events, an OpenAPI spec and test keys in an isolated environment. From the Free plan.',
        plan: 'On every plan. Free includes 2 keys and 100 calls a month; test keys do not count against your quota.',
        heroMock: 'hero-api',
        updated: UPDATED,
        blocks: [
            {
                eyebrow: 'IDEMPOTENCY',
                titulo: 'Retry without fear of duplicates.',
                copy: 'A flaky network should not create two quotes. Send an Idempotency-Key on any POST, PATCH or DELETE: if the request repeats with the same key and body, Cord returns the original response, marked Idempotent-Replayed, instead of running twice. If the body changed, you get an explicit error.',
                bullets: [
                    'Works on every mutation under /api/v1',
                    'The replayed response is identical, byte for byte',
                    'Same key with a different body: an error, never a silent duplicate',
                ],
                mock: 'code-idempotency',
            },
            {
                eyebrow: 'KEYS',
                titulo: 'Keys with their own permission and environment.',
                copy: 'Each key is read or write, and lives in test or live. Secret keys (sk_) belong on your server; publishable keys (pk_) can go in the browser with a narrow scope. Revoke one in a click and it stops working instantly. Only its hash is stored.',
                bullets: [
                    'sk_test_ runs against a test environment separate from your real data',
                    'Last used and created dates in plain sight',
                    'Per-key limit: 600 per minute for secret keys, 120 for publishable',
                ],
                mock: 'wb-keys',
            },
            {
                eyebrow: 'RESOURCES',
                titulo: 'What you see in the app, also over the API.',
                copy: 'This is not a read-only API. Create a quote and send it, approve it or mark it paid. Create an invoice as a draft and issue it, email it, record a payment or a credit note. All with the same permissions, validation and totals the app uses.',
                bullets: [
                    'Quotes, invoices, clients, products, tasks and collections',
                    'Actions via POST { "action": "send" | "approve" | "finalize" | … }',
                    'Pagination with limit and offset, or a cursor for events and invoices',
                ],
                mock: 'wb-endpoints',
            },
            {
                eyebrow: 'EVENTS',
                titulo: 'Sync without missing a thing.',
                copy: "GET /api/v1/events returns your business history, newest first: quotes sent, viewed, approved or paid, invoices issued, new clients. Filter by type or object and page with next_cursor. It is the webhooks' companion for rebuilding any state.",
                bullets: [
                    'Filters ?type=quote.approved and ?object_id=',
                    'Up to 200 events per page with a stable cursor',
                    'The same types your webhooks receive',
                ],
                mock: 'code-events',
            },
        ],
        steps: [
            { titulo: 'Create a test key', copy: "In the developer Workbench, API tab, with Test mode on. It's shown only once." },
            { titulo: 'Make your first call', copy: 'GET https://cordhq.app/api/v1/me with an Authorization: Bearer header. It tells you which business the key belongs to.' },
            { titulo: 'Go live', copy: 'Switch to Live, generate an sk_live_ key and point your integration at it. The code does not change.' },
        ],
        faqs: [
            { q: 'What is the Cord API?', a: 'A REST API at https://cordhq.app/api/v1 that gives programmatic access to your quotes, invoices, clients, products, tasks, collections and events. It authenticates with a Bearer key and responds in JSON shaped as { data, meta } or { error, code }.' },
            { q: 'Do I need a paid plan to use the API?', a: 'No. The API is on every plan, including Free, with 2 keys and 100 calls a month. Starter includes 1,000 calls, Professional 5,000, Scale 10,000 and Developer 50,000. Test keys do not count against your quota.' },
            { q: 'How do I test without touching real data?', a: 'Use an sk_test_ key. It runs against a test environment separate from your account, so you can create and delete quotes without affecting your clients or your reports.' },
            { q: 'How do I avoid duplicate records when I retry?', a: 'Send the Idempotency-Key header. If you repeat the request with the same key and body, Cord returns the original response without running it again.' },
            { q: 'Is there an OpenAPI spec?', a: 'Yes, at https://cordhq.app/openapi.yaml, plus an AI-assistant summary at https://cordhq.app/llms.txt. Both are linked from the Workbench.' },
        ],
        cta: { titulo: 'Make your first call today.', sub: 'Create your account, generate a test key and call /api/v1/me in under a minute.' },
        trust: {
            eyebrow: 'API DETAILS',
            titulo: 'What you notice when you integrate for real',
            items: [
                { icon: 'doc', titulo: 'Flat errors with stable codes', copy: 'Every error arrives as { error, code } with a code that does not change —invalid_request, rate_limited, api_quota_exceeded— so your error handling never parses messages.' },
                { icon: 'gauge', titulo: 'A 429 tells you how long to wait', copy: 'When you hit the per-minute limit you get Retry-After. Running out of monthly quota uses a different code, so you never confuse the two.' },
                { icon: 'key', titulo: 'Keys are never stored in plain text', copy: 'Only a hash exists in the database. If you lose a key you create another; nobody at Cord can recover it.' },
            ],
        },
    },
    {
        slug: 'workbench',
        nav: 'Workbench',
        eyebrow: 'DEVELOPER WORKBENCH',
        titulo: 'Your whole integration, in a panel inside the app.',
        sub: "Cord's Workbench is a developer panel that opens inside the app, over whatever screen you're on. It brings together API keys, webhooks, a log of every request, business events and your integration's health, with a test mode kept apart from your real data.",
        metaTitle: 'Developer Workbench: API logs, webhooks and health — Cord',
        metaDescription: "Cord's Workbench shows every API request with its status and latency, manages signed webhooks, test and live keys, and flags failing endpoints. Included on every plan.",
        plan: 'Included on every plan. Any member with access to Settings can open it.',
        heroMock: 'hero-workbench',
        updated: UPDATED,
        blocks: [
            {
                eyebrow: 'LOGS',
                titulo: 'Every request, with its response.',
                copy: 'Search by route, filter by method or response class and open any request to see its status, latency, IP, the key that made it and the environment. When something fails you know within seconds whether it was a 401 from a revoked key or a 422 from a malformed field.',
                bullets: [
                    'Filters by method (GET, POST) and class (2xx, 4xx, 5xx)',
                    'Detail shows the calling key by name',
                    'Cord does not store your request bodies: only metadata',
                ],
                mock: 'wb-logs',
            },
            {
                eyebrow: 'WEBHOOKS',
                titulo: 'Endpoints you can test without waiting for a real event.',
                copy: "Register a URL, pick the events and save the secret. Test sends a delivery right away, Rotate secret changes the signature without cutting traffic, and each endpoint's history shows its deliveries with the code your server returned.",
                bullets: [
                    'X-Cord-Signature-V1 signature with a timestamp',
                    'Secret rotation with a grace period',
                    'Pause an endpoint with a switch, without deleting it',
                ],
                mock: 'wb-webhooks',
            },
            {
                eyebrow: 'HEALTH',
                titulo: 'Find out before your customer does.',
                copy: "The Health tab gathers what can break an integration: endpoints with consecutive failures, queued or exhausted events, and the routes returning the most errors. If an endpoint keeps failing you see it here and get a notice before Cord disables it.",
                bullets: [
                    'Consecutive failures per endpoint',
                    'Event queue: pending, overdue and exhausted',
                    'Routes with the most 4xx and 5xx errors',
                ],
                mock: 'wb-health',
            },
        ],
        steps: [
            { titulo: 'Open the panel', copy: 'From the "Developers" bar at the bottom of the app. It opens over the screen you are on.' },
            { titulo: 'Pick the environment', copy: 'Test to integrate safely, Live for production. Keys and data for each are kept apart.' },
            { titulo: 'Build and watch', copy: 'Generate your key, register a webhook and follow every request in Logs while you build.' },
        ],
        faqs: [
            { q: "What is Cord's Workbench?", a: "It's Cord's developer panel. It opens inside the app and brings together API keys, webhooks, the request log, business events and integration health, with a separate test mode." },
            { q: 'What does Cord keep from each API request?', a: 'Method, route, response code, latency, IP, the key and the environment. It does not store request or response bodies, so your clients\' data is not kept outside where it belongs.' },
            { q: 'What happens if my webhook endpoint stops responding?', a: 'Cord retries each delivery up to 11 times with growing waits, over almost four days. If the endpoint keeps failing you see it in Health and get a notice; after 5 consecutive failures Cord disables it instead of hammering a server that is down.' },
            { q: 'Who can open the Workbench?', a: 'Any member of the organization with access to Settings. It is included on every plan.' },
        ],
        cta: { titulo: 'Integrate with your eyes open.', sub: 'Create your account, open the Workbench and follow your first request live.' },
        trust: {
            eyebrow: 'PANEL DETAILS',
            titulo: 'Built for working, not for watching',
            items: [
                { icon: 'toggle', titulo: 'Times in UTC or your timezone', copy: "A switch in the panel menu flips every timestamp, handy when you compare against your server's logs." },
                { icon: 'layers', titulo: 'Stays where you left it', copy: 'The panel resizes, maximizes and remembers the last tab you opened.' },
                { icon: 'lock', titulo: 'The secret is shown only once', copy: 'When you create an endpoint or rotate its secret you copy it then; afterwards it stays masked.' },
            ],
        },
    },
    {
        slug: 'mcp',
        nav: 'MCP server',
        eyebrow: 'MCP SERVER',
        titulo: 'Your business, available to Claude, Cursor and any agent.',
        sub: "Cord's MCP server connects AI assistants like Claude or Cursor to your real business data through the Model Context Protocol. With 19 tools the AI reads quotes, invoices and overdue receivables, and with a write key it can also create drafts, send quotes or record payments.",
        metaTitle: 'MCP server for Claude and Cursor: quotes and invoices with AI — Cord',
        metaDescription: 'Connect Claude, Cursor or any MCP client to Cord with your API key. 19 tools: 9 read (quotes, invoices, overdue receivables) and 10 write (drafts, sending, payments). On every plan.',
        plan: 'On every plan. It uses the same API key as the REST API; write tools require a key with write permission.',
        heroMock: 'hero-mcp',
        updated: UPDATED,
        blocks: [
            {
                eyebrow: 'CONNECTION',
                titulo: 'Paste one config block and you are done.',
                copy: 'In Settings › MCP you copy the exact config for Claude Desktop, for Cursor, or the direct URL for any other client. The connection is https://cordhq.app/api/mcp with your key in the Authorization header. For clients that need a session, Cord also exposes an SSE channel.',
                bullets: [
                    'Stateless JSON-RPC 2.0 over HTTP',
                    'Session-based SSE channel at /api/mcp/sse',
                    'The same key you already use for the REST API',
                ],
                mock: 'mcp-connect',
            },
            {
                eyebrow: 'TOOLS',
                titulo: '19 tools, each with its own permission.',
                copy: 'The AI can ask "which invoices are overdue?" or "how is the business doing?" with the 9 read tools. With a write key it can also draft a quote or an invoice, send a quote, mark it approved or paid, add a client or record a promise to pay.',
                bullets: [
                    'Read: quotes, invoices, clients, products, events and receivables',
                    'Write: only with a key that has that permission',
                    'Paginated results with next_cursor, just like the API',
                ],
                mock: 'mcp-tools',
            },
            {
                eyebrow: 'PLAYGROUND',
                titulo: 'See exactly what the AI receives.',
                copy: 'Before configuring a client, try any read tool from Settings › MCP against your real data. Pick the tool, pass JSON arguments and see the response exactly as the model gets it. Write tools do not run there, so nothing is created by accident.',
                bullets: [
                    'Runs with your session, no key to configure',
                    'Optional JSON arguments, such as {"limit": 5}',
                    'Read tools only',
                ],
                mock: 'mcp-playground',
            },
        ],
        steps: [
            { titulo: 'Generate a key', copy: 'In the Workbench, API tab. Read-only if the AI will only look things up; write if it will also create drafts.' },
            { titulo: 'Copy the config', copy: 'Settings › MCP has the block ready for Claude Desktop, Cursor or the direct URL. Replace the sample key with yours.' },
            { titulo: 'Ask in plain language', copy: '"Which clients owe me more than 30 days?" The AI picks the tool and answers with your data.' },
        ],
        faqs: [
            { q: "What is Cord's MCP server?", a: 'A Model Context Protocol server at https://cordhq.app/api/mcp that exposes 19 tools over your business data. Any MCP client, such as Claude Desktop or Cursor, can use them by authenticating with your Cord API key.' },
            { q: 'Can the AI change my data?', a: 'Only if you give it a key with write permission. With a read key, the 10 write tools answer that the action requires that permission and run nothing.' },
            { q: 'What can I ask Claude about my business?', a: 'Things like which invoices are overdue, how the pipeline looks, what happened with a quote or how much a client owes you. With a write key you can also ask it to draft a quote for you to review before sending.' },
            { q: 'If the AI retries, can it duplicate a quote?', a: 'No. The crear_cotizacion_borrador tool accepts an idempotency_key: a retry with the same key returns the quote already created instead of making another.' },
            { q: 'Do I need a separate key for MCP?', a: 'No. It is the same API key as the REST API, in the same Authorization: Bearer header.' },
        ],
        cta: { titulo: 'Ask your business.', sub: 'Create your account, copy the config for Claude or Cursor and ask your first question.' },
        trust: {
            eyebrow: 'PROTOCOL DETAILS',
            titulo: 'What we take care of so the AI gets it right',
            items: [
                { icon: 'doc', titulo: 'A business error does not break the conversation', copy: 'A missing client or a missing permission comes back as isError inside the result. The AI reads it, explains it and moves on, with no transport error.' },
                { icon: 'shield', titulo: "Your client's text is data, not instructions", copy: 'Events your client writes on the public link arrive tagged with their origin, and the tools tell the model to report them, never to obey them.' },
                { icon: 'lock', titulo: 'Every call lives inside your organization', copy: 'The key resolves to your organization and every query runs in its context; a tool cannot read another business\'s data.' },
            ],
        },
    },
    {
        slug: 'integraciones',
        nav: 'Webhooks and integrations',
        eyebrow: 'WEBHOOKS · INTEGRATIONS',
        titulo: 'Let your system hear about every sale, the moment it happens.',
        sub: "Cord's webhooks notify your server every time something happens in your sales cycle: a quote sent, viewed, approved or paid, an invoice issued, a new client. Each notice is a JSON POST signed with HMAC-SHA256, with automatic retries and a history you can review in the Workbench.",
        metaTitle: 'Signed webhooks for quotes and invoices (Zapier, Make, n8n) — Cord',
        metaDescription: '41 sales events —quote.approved, quote.paid, invoice.finalized— delivered as a POST signed with HMAC-SHA256, with 11 retries. Send them to your backend, Zapier, Make or n8n. On every plan.',
        plan: 'On every plan: 16 endpoints on Free, Starter and Professional, 32 on Scale and 100 on Developer.',
        heroMock: 'hero-webhook',
        updated: UPDATED,
        blocks: [
            {
                eyebrow: 'SIGNATURE',
                titulo: 'Verify the notice came from Cord.',
                copy: "Every delivery carries X-Cord-Signature-V1 with a timestamp and the HMAC-SHA256 of the raw body, signed with your endpoint's secret. You validate it in a few lines before processing the event, and the timestamp protects you from someone replaying an old delivery.",
                bullets: [
                    'X-Cord-Event-Id to deduplicate without reading the body',
                    'X-Cord-Attempt tells you which delivery attempt it is',
                    'During a rotation it signs with both the new and the previous secret',
                ],
                mock: 'code-verify',
            },
            {
                eyebrow: 'ENDPOINTS',
                titulo: 'Configure, test and pause from the Workbench.',
                copy: "Register a URL and choose the events you care about. Test sends a delivery without waiting for something real to happen, and each endpoint's history shows what your server answered on every attempt. If your server goes down, Cord keeps retrying for almost four days.",
                bullets: [
                    'Test delivery in one click',
                    'Secret rotation without cutting traffic',
                    'After 5 consecutive failures the endpoint pauses and you get a notice',
                ],
                mock: 'wb-webhooks',
            },
            {
                eyebrow: 'CATALOG',
                titulo: '41 events for the whole sales cycle.',
                copy: 'Not just quotes. Get notices for invoices finalized, sent, paid or overdue, partial or failed payments, refunds, disputes, payouts, clients, products, tasks and promises to pay. Subscribe each endpoint only to what it needs.',
                bullets: [
                    'quote.* · invoice.* · payment.* · refund.* · payout.*',
                    'client.* · product.* · task.* · promise.* · dispute.*',
                    'The same types GET /api/v1/events returns',
                ],
                mock: 'event-catalog',
            },
            {
                eyebrow: 'NO CODE',
                titulo: 'Zapier, Make and n8n, without copying keys.',
                copy: 'Zapier and Make connect to Cord with OAuth: you authorize the app once and it shows up in the Workbench as an authorized connection you can revoke anytime. n8n uses an API key. All three create their own webhook subscriptions, with a separate allowance of 100 that does not use up your team\'s endpoints.',
                bullets: [
                    'OAuth authorization for Zapier and Make',
                    'Revoke an app without touching your keys',
                    'HubSpot, Slack and Microsoft Teams connect directly from Settings',
                ],
                mock: 'oauth-apps',
            },
        ],
        steps: [
            { titulo: 'Register your endpoint', copy: 'In the Workbench, Webhooks tab: paste the URL, pick the events and copy the secret, shown only once.' },
            { titulo: 'Verify the signature', copy: 'Compute the HMAC-SHA256 of "timestamp.body" with your secret and compare it to X-Cord-Signature-V1.' },
            { titulo: 'Answer 2xx fast', copy: 'Reply within 5 seconds and process in the background. Deduplicate by X-Cord-Event-Id.' },
        ],
        faqs: [
            { q: 'What is a Cord webhook?', a: 'An automatic notice: when an event happens in your account, such as an approved quote or a paid invoice, Cord sends a JSON POST to the URL you registered, signed with HMAC-SHA256 so you can verify where it came from.' },
            { q: 'What if my server does not respond?', a: 'Cord retries up to 11 times with growing waits over almost four days, with a 5-second timeout per attempt. After 3 consecutive failures you get a notice and after 5 the endpoint is disabled until you turn it back on.' },
            { q: 'How do I avoid processing the same event twice?', a: 'Use X-Cord-Event-Id, which also travels as the id field in the body. It stays the same across every retry of an event, so you only need to store the ones you already handled.' },
            { q: 'Does Cord have a native connector for SAP, Salesforce or Oracle?', a: 'No. Direct connections exist for HubSpot, Slack and Microsoft Teams, among others. For SAP, Salesforce or Oracle you point a webhook at your backend or at Zapier, Make or n8n, and use the REST API to write back into Cord.' },
            { q: 'How many endpoints can I have?', a: '16 on Free, Starter and Professional, 32 on Scale and 100 on Developer. Subscriptions created by Zapier, Make or n8n have a separate allowance of 100 per organization.' },
        ],
        cta: { titulo: 'Receive your first event in minutes.', sub: 'Register an endpoint in the Workbench and hit Test to watch the delivery arrive.' },
        trust: {
            eyebrow: 'HOW IT BEHAVES',
            titulo: 'What happens when something fails',
            items: [
                { icon: 'refresh', titulo: 'Durable delivery, not best effort', copy: 'The event is saved before any delivery attempt. If the process is interrupted the notice is not lost: it stays queued until delivered or out of attempts.' },
                { icon: 'gauge', titulo: 'Retries with random jitter', copy: 'Waits carry a ±20% margin so many failing endpoints do not receive all their retries in the same second.' },
                { icon: 'key', titulo: 'Rotation with no blind window', copy: 'When you rotate the secret, Cord signs with both the new and the previous one during the grace period, so your server can update without rejecting deliveries.' },
            ],
        },
    },
    {
        slug: 'elements',
        nav: 'Cord Elements',
        eyebrow: 'CORD ELEMENTS · EMBEDDABLE QUOTE BUILDER',
        titulo: "Your quote builder, inside your client's site.",
        sub: "Cord Elements brings your quotes into your clients' portal with one line of code. They see your brand, review every line item, approve with a signature, negotiate or pay without leaving their site, and your page receives every step as a typed event.",
        metaTitle: 'Cord Elements — embeddable quote builder for React, Vue and HTML',
        metaDescription: 'Embed your quotes on any site with one line: embed.js, the <cord-cotizador> Web Component or @flouviahq/elements for React, Vue, Framer and Webflow. Signed approval, online payment and 8 typed events.',
        plan: 'On every plan, including Free. From Starter you remove Cord branding in Settings › Brand appearance; the domains allowed to embed it are set in Settings › Embeddable quote builder.',
        updated: UPDATED,
        blocks: [
            {
                eyebrow: 'ONE LINE OF CODE',
                titulo: 'Paste. Done. No backend.',
                copy: "A script and a <div>. The quote builder appears as an iframe served by Cord, measures its content and tells your page so the height adjusts on its own. There is no server to maintain and no data to sync: the quote's public token is all you need.",
                bullets: [
                    'WordPress, Webflow, Shopify or plain HTML: any site that accepts a script',
                    'Automatic height: no scrollbars, no empty boxes',
                    'The same quote builder as the public /q link, with no extra code',
                ],
            },
            {
                eyebrow: 'YOUR BRAND',
                titulo: 'With your identity, or with their portal\'s.',
                copy: 'Logo, color and business name come from your account. If the host portal has its own style, the Appearance API sets a light, dark or automatic theme, the primary color, radii and a typeface from Google Fonts or Bunny Fonts.',
                bullets: [
                    "theme: light, dark or auto, which follows the client's system",
                    'variables: colorPrimary, colorText, colorBackground, borderRadius',
                    'Values sanitized on the server: a theme cannot inject arbitrary CSS',
                ],
            },
            {
                eyebrow: 'EVENTS',
                titulo: 'Your page hears about every step your client takes.',
                copy: 'When the client opens, approves, rejects, writes or pays, the iframe tells your page with a typed event and its detail. With React or Vue they arrive as callbacks; with the Web Component, as DOM events. Use them to redirect, open your checkout or notify your CRM.',
                bullets: [
                    'onApproved carries signed_by and the signature hash',
                    "onPay carries the payment URL; onRejected, the client's comment",
                    "With an allowlist, events are sent only to your site's origin",
                ],
            },
            {
                eyebrow: 'HEADLESS',
                titulo: 'Or build your own interface on top of our state.',
                copy: "If you don't want our design, useQuoteBuilder() gives you the full state to put together a new quote from your own UI: line items, client, subtotal, taxes and total, computed with the same engine as the server. You bring the markup; Cord creates the quote and returns its link.",
                bullets: [
                    'A pk_ publishable key in the browser, or your own proxy with an sk_',
                    'Stable .cord-* classes and styles inside @layer cord: your CSS always wins',
                    'baseTheme: "none" to inject no CSS at all',
                ],
            },
        ],
        steps: [
            { titulo: 'Copy your snippet', copy: 'embed.js for any site, or npm install @flouviahq/elements if you use React, Vue, Framer or Webflow.' },
            { titulo: 'Pass the token', copy: "The quote's public token. Your brand and your details come from your Cord account." },
            { titulo: 'Listen to events', copy: 'onApproved, onPay and the rest to redirect, collect or sync your CRM in real time.' },
        ],
        faqs: [
            { q: 'What is Cord Elements?', a: "It's Cord's SDK for showing your quotes inside another site. It includes a one-line loader (embed.js), the <cord-cotizador> Web Component, wrappers for React, Vue, Framer and Webflow, a headless hook to build quotes with your own UI and a Server SDK to verify webhooks." },
            { q: 'Do I need my own backend?', a: 'Not to show a quote: the iframe talks directly to Cord and the public token is enough. To create quotes from the browser you use a narrowly scoped publishable key (pk_); if you would rather expose no key at all, your backend acts as a proxy with a secret key (sk_).' },
            { q: "Can I use it without Cord's interface?", a: 'Yes. useQuoteBuilder() exposes the quote builder state (line items, client, totals and submission) without rendering anything of ours, and with baseTheme: "none" the SDK injects no CSS.' },
            { q: 'Who can embed my quotes?', a: 'You decide. In Settings › Embeddable quote builder you list the allowed domains and Cord enforces them with the frame-ancestors header, so no other site can show them inside an iframe. With no list, the embed stays open.' },
            { q: 'Can I remove Cord branding?', a: 'Yes, from the Starter plan, in Settings › Brand appearance. On the Free plan the quote shows a discreet Cord notice at the bottom.' },
            { q: 'Can the client pay inside the embed?', a: 'Yes, when Cord Payments is active. The pay button fires the pay event with the payment URL, so your page decides whether to open it in the same tab or a new one.' },
        ],
        cta: { titulo: 'Bring your quote builder to where your clients are.', sub: 'Create your free account and embed your first quote today.' },
    },
    {
        slug: 'fx',
        nav: 'Multi-currency',
        eyebrow: 'MULTI-CURRENCY · EXCHANGE RATES',
        titulo: "Sell in your client's currency. Keep your books in yours.",
        sub: 'Cord keeps the currency you sell in apart from the currency you keep your books in. You quote and collect in dollars or euros, the exchange rate is frozen at quote time from a published, dated source, and the invoice declares that rate and the total in your ledger currency. If there is no real rate, Cord does not make one up.',
        metaTitle: 'Multi-currency quotes and invoices with a locked exchange rate — Cord',
        metaDescription: 'Quote in USD or EUR and keep your books in MXN: Cord locks the exchange rate for 30 days from a published source (ECB first) and the invoice declares the rate and the ledger total. Available over the API.',
        plan: 'On every plan. The API accepts base_currency, fiscal_currency and fx_buffer_pct when creating a quote.',
        heroMock: 'hero-fx',
        updated: UPDATED,
        blocks: [
            {
                eyebrow: 'TWO CURRENCIES, TWO JOBS',
                titulo: 'The sales currency and the ledger currency never mix.',
                copy: 'The sales currency is the one your client sees: prices are entered in it, the link shows it, you collect in it and the invoice is issued in it. The ledger currency is the one in your books. When they differ, the invoice declares the exchange rate and the converted total; amounts are never relabeled.',
                bullets: [
                    'base_currency: the currency you sell and collect in',
                    'fiscal_currency: your accounting currency',
                    'The invoice returns tipo_cambio and total_contable over the API',
                ],
                mock: 'fx-invoice',
            },
            {
                eyebrow: 'LOCKED RATE',
                titulo: 'Your margin does not move mid-negotiation.',
                copy: "When the quote is created, Cord takes the day's rate and locks it for 30 days. You can add a cushion with fx_buffer_pct to cover that client's volatility. That same rate is what the invoice uses later: there are never three different calculations for one sale.",
                bullets: [
                    'A cushion per quote, not one fixed for the whole account',
                    'The same rate on the quote, the payment and the invoice',
                    'A cached rate is only valid if it is under 24 hours old',
                ],
                mock: 'code-fx',
            },
            {
                eyebrow: 'SOURCES',
                titulo: 'If no source publishes the pair, Cord stops.',
                copy: "Cord first checks the European Central Bank's daily reference. Since it publishes around 30 currencies, for pairs such as COP, CLP, PEN or ARS it moves on to two broad-coverage sources. If none has the pair, the quote is not created and the message says why. A made-up rate of 1.0 never reaches your invoice.",
                bullets: [
                    'European Central Bank as the first reference',
                    'Two fallback sources for Latin American currencies',
                    '"This source does not cover the pair" and "no response" are handled differently',
                ],
                mock: 'fx-sources',
            },
        ],
        steps: [
            { titulo: 'Set your ledger currency', copy: "In Settings, your business's currency. It's the one your reports and books use." },
            { titulo: "Quote in the client's currency", copy: 'In the editor or over the API with base_currency. Optionally add a cushion with fx_buffer_pct.' },
            { titulo: 'Invoice with the locked rate', copy: 'The invoice declares the exchange rate and the ledger total, ready for your accounting.' },
        ],
        faqs: [
            { q: 'Which source does Cord use for exchange rates?', a: "First the European Central Bank's daily reference, through Frankfurter. For currencies the ECB does not publish, such as COP, CLP, PEN or ARS, it checks two broad-coverage sources in order. If none has the pair, the operation stops with a clear message." },
            { q: 'How long is the rate locked?', a: '30 days from when the quote is created. During that time the rate does not change even if the market moves.' },
            { q: 'Can I quote in dollars and keep my books in pesos?', a: 'You can quote, collect and invoice in dollars while your accounting stays in pesos: the invoice declares the locked exchange rate and the total in your ledger currency. In Mexico, the CFDI is issued in the sale currency with its exchange rate.' },
            { q: 'What happens if no exchange rate is available?', a: 'Cord does not create the quote and returns a clear error (503 on the API). It only uses a cached rate if it is under 24 hours old; it never substitutes 1.0 or an estimate.' },
        ],
        cta: { titulo: 'Sell in any currency without losing your margin.', sub: 'Create your account and quote in dollars or euros with a locked rate.' },
        trust: {
            eyebrow: 'DETAILS THAT MATTER',
            titulo: 'Money, not loose numbers',
            items: [
                { icon: 'doc', titulo: 'Every amount travels with its currency', copy: 'No amount is shown with a default "$": the symbol comes from the sale currency on the link, the PDF and the email.' },
                { icon: 'gauge', titulo: 'Correct minor units per currency', copy: 'The yen and the Chilean peso have no cents; the Kuwaiti dinar has three decimals. Payments use the right unit for each currency.' },
                { icon: 'route', titulo: 'Conversion runs from sales to ledger', copy: 'It always multiplies in the same direction. The editor preview and the database give the same number.' },
            ],
        },
    },
    {
        slug: 'fiscal',
        nav: 'Tax invoicing',
        eyebrow: 'TAX INVOICING',
        titulo: 'Legal invoices in Mexico, commercial everywhere else, over the API.',
        sub: "Cord Invoicing issues invoices from the app or over the API and adapts the document to your business's country: CFDI 4.0 stamped with Mexico's SAT, and a commercial invoice with each country's taxes everywhere else. Spain has the Verifactu registry built and in the process of activation with the AEAT.",
        metaTitle: 'Invoicing API: CFDI 4.0 in Mexico and invoices by country — Cord',
        metaDescription: 'Create, issue and collect invoices over the API: CFDI 4.0 stamped with the SAT in Mexico, per-line and per-country taxes, partial payments and credit notes. Verifactu built for Spain.',
        plan: 'Tax issuing is available from the Starter plan where enabled. Free issues commercial documents.',
        heroMock: 'hero-fiscal',
        updated: UPDATED,
        blocks: [
            {
                eyebrow: 'FULL CYCLE',
                titulo: 'Create, issue, collect and correct from your code.',
                copy: 'POST /api/v1/facturas creates a draft. Then, on that same invoice, you issue it, email it with the PDF attached, record a full or partial payment, void it or create a credit note. Each action fires its event, so your system can react by webhook.',
                bullets: [
                    'Draft first: nothing is stamped until you issue',
                    'Partial payments capped at the real balance',
                    'invoice.finalized, invoice.paid and invoice.voided as webhooks',
                ],
                mock: 'code-invoice',
            },
            {
                eyebrow: 'INVOICES IN THE APP',
                titulo: 'Your team sees what your integration sees.',
                copy: 'What you create over the API shows up in Invoices with its commercial and tax status: open, overdue, paid or void, and whether issuing failed. Open, overdue and collected this month are calculated for you.',
                bullets: [
                    'Commercial status and tax status kept apart',
                    'Balance and due date for each invoice',
                    'CSV export and recurring invoices',
                ],
                mock: 'app-invoices',
            },
            {
                eyebrow: 'BY COUNTRY',
                titulo: 'The right document for each country.',
                copy: "In Mexico, Cord stamps CFDI 4.0 with the SAT using your digital seal certificate through an authorized provider. Everywhere else it issues a commercial invoice with that country's per-line taxes, such as state sales tax in the United States or VAT and IRPF in Spain. For Spain, the Verifactu registry with a chained SHA-256 hash is built and verified against the AEAT's official examples; it goes live once registration with the AEAT is complete.",
                bullets: [
                    'Mexico: CFDI 4.0 with the SAT UUID, PDF and XML',
                    'Per-line taxes and withholdings, not a flat rate',
                    'Spain: Verifactu built, pending activation with the AEAT',
                ],
                mock: 'fiscal-countries',
            },
        ],
        steps: [
            { titulo: 'Set up your tax details', copy: 'In Settings: your tax ID and, in Mexico, your tax regime, postal code and CSD.' },
            { titulo: 'Create the draft', copy: 'POST /api/v1/facturas with cliente_id and line items, or from an approved quote in the app.' },
            { titulo: 'Issue and collect', copy: 'POST /api/v1/facturas/{id} with action finalize. Record payments with action payment.' },
        ],
        faqs: [
            { q: 'Does Cord stamp real CFDI 4.0?', a: 'Yes. In Mexico, Cord stamps CFDI 4.0 with the SAT using your digital seal certificate (CSD) through an authorized provider (PAC), and returns the UUID, the PDF and the XML.' },
            { q: 'Can I issue invoices over the API?', a: 'Yes. POST /api/v1/facturas creates a draft and POST /api/v1/facturas/{id} with action finalize issues it. The same route accepts send, payment, void and credit_note.' },
            { q: 'Does Cord issue tax invoices in the United States?', a: 'Cord issues commercial invoices with state sales tax. The United States has no national e-invoicing system like the CFDI, so the commercial invoice is the usual document.' },
            { q: 'Does Cord already register invoices with the AEAT through Verifactu?', a: 'Not yet. The Verifactu registry is built and verified against the AEAT\'s official examples, but going live depends on Cord\'s registration as the software producer with the AEAT. Until then, invoices in Spain are issued as commercial invoices.' },
            { q: 'What happens if issuing fails?', a: 'The invoice keeps the tax status "error" and is not marked as issued. You see it in the app and over the API, and can fix the data and issue again.' },
        ],
        cta: { titulo: 'Invoice from your system, with the right document.', sub: 'Create your account, set up your tax details and issue your first invoice over the API.' },
        trust: {
            eyebrow: 'NON-NEGOTIABLE',
            titulo: 'A legal document is not a PDF with a number',
            items: [
                { icon: 'lock', titulo: 'A draft is never stamped', copy: 'Nothing reaches the SAT until you issue. Cancelling a CFDI requires the recipient\'s acceptance, so Cord never stamps ahead of time.' },
                { icon: 'doc', titulo: 'The tax rate is stored with the line', copy: 'Changing your tax catalog later does not rewrite an invoice already issued.' },
                { icon: 'refresh', titulo: 'Payments are never applied twice', copy: 'A retry from the payment processor does not duplicate a payment: each one is applied to the invoice only once.' },
            ],
        },
    },
];

export const findDevPageEn = (slug: string) => DEV_PAGES_EN.find((p) => p.slug === slug);
